### ISSUE TITLE
Improvement: Implement a "polling" poll

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/kda-tool#13]
kda-tool should have a "polling" poll command.

- Maybe by creating new command
- Or maybe by adding a parameter to the poll command.

This command should poll the node (every x seconds) and return only when the transaction has been mined (with failure or success). In fact exactly how Chainweaver actually does.

A timeout is although necessary.

**Comment by mightybyte** [comment]
This is pretty trivial to achieve in a shell script with a loop and delay.
