### ISSUE TITLE
Imrpovement: Allow to concatenate several code files

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/kda-tool#14]
The `codeFile` parameter of the template should allow to use a list with several files. 
The tool would concatenate them when building the transaction.

This is especially useful when pre-fixing or post-fixing a contract.

For example
- pre-fixing can be used to set the namespace, create a keyset, ...
- post-fixing can be used to add some init code (table creation, ....) that makes sense to keep separate from the main contract file.
 
 This can be useful as well to deploy 2 contracts inside the same transaction.

**Comment by mightybyte** [comment]
This can be pretty easily handled externally with custom scripts that concatenate files before invoking kda-tool.  This feature would also cause problems with the current list behavior, so I think these use cases should be handled outside kda-tool.
