### ISSUE TITLE
Imrpovement: Allow to create a "product" of data 

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/kda-tool#15]
When there are several lists is in the "data YAML" file (the one used to fill the template), the lists are "zipped". 
And thus, they must have the same length.

In my opinion, it would be more useful to make a product  between them.

Example:
In my project I have 5 contracts that I want to deploy on 20 chains. I would like the tool to generate automatically the 100 transactions, by making a product of `{{chain}} =  [1,2,3,4,5, 6, 7, .... ]` by the `{{file}} = [cont_one.pact, cont_two.pact, cont_three.pact, cont_four.pact,  contract_five.pact] `

You could imagine as well somebody who would want to do several "same transfers" on different chains.

**Comment by mightybyte** [comment]
I think the current "zip" behavior is much more intuitive for the user.  You can also achieve the product behavior externally by using the current behavior in a loop.  However the reverse is not true, so I'm inclined to keep the current "zip" behavior.
